faaast-service:
  messageBus:
    host: "wss://local.broker.url:443"
    user: "faaast-messagebus-user"
    password: "faaast-messagebus-pw"

aas-basyx-v2-full:
  mqtt:
    enabled: true
    websockets:
      enabled: true
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
       kubernetes.io/ingress.class: nginx
       kubernetes.io/tls-acme: "true"
       nginx.ingress.kubernetes.io/enable-cors: "true"
       cert-manager.io/cluster-issuer: "letsencrypt-prod"
       nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
       nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
       nginx.ingress.kubernetes.io/websocket-services: mqttbroker-websockets-service
      hosts:
        - host: local.broker.url
          type: websockets
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: chart-example-tls
          hosts:
            - local.broker.url
    apirules: []
    auth:
      enabled: true
      users:
        - username: fx-factory
          password: fx-factory-pw-hash
          acl:
            - topic: "#"
              access: readwrite
        - username: fx-publisher
          password: fx-publisher-pw-hash
          acl:
            - topic: "#"
              access: readwrite
        - username: fx-subscriber
          password: fx-subscriber-pw-hash
          acl:
            - topic: "#"
              access: readwrite
        - username: fx-factory2
          password: fx-factory2-pw-hash
          acl:
            - topic: "#"
              access: readwrite
        - username: fx-publisher2
          password: fx-publisher2-pw-hash
          acl:
            - topic: "#"
              access: readwrite
        - username: fx-subscriber2
          password: fx-subscriber2-pw-hash
          acl:
            - topic: "#"
              access: readwrite

  keycloak:
    enabled: true
    postgresql:
      enabled: true
      auth:
        username: keycloak-postgres-user
        password: keycloak-postgres-pw
        database: keycloak-postgres-db
    ingress:
      enabled: true
      hostname: local.keycloak.url
    auth:
      adminUser: keycloak-user
      adminPassword: keycloak-pw

  aas-registry:
    enabled: true
    image:
            # If Kafka is used, then the appropriate Bootstrap connection string must be provided.
      name: eclipsebasyx/aas-registry-log-mem:2.0.0-SNAPSHOT
      pullPolicy: IfNotPresent
    service:
      port: 8080
    # Keep it null if not deploying a Kafka instance.
    kafka:
      connectionString: null
    ingress:
      enabled: true
      host: local.basyx.reg.url
    config: |-
      basyx:
        cors:
          allowed-origins: "*"
          allowed-methods: "GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD"


  sm-registry:
    enabled: false

  aas-discovery:
    enabled: true
    image:
      name: eclipsebasyx/aas-discovery:2.0.0-SNAPSHOT
      pullPolicy: IfNotPresent
    service:
      port: 8081
    config: |-
      server.port=8081
      spring.application.name=AAS Discovery Service

      basyx.aasdiscoveryservice.name=aas-discovery-service

      basyx.backend=InMemory

      basyx.cors.allowed-origins=*
      basyx.cors.allowed-methods=GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD

      basyx.feature.authorization.enabled = false
      basyx.feature.authorization.type = rbac
      basyx.feature.authorization.jwtBearerTokenProvider = keycloak
      basyx.feature.authorization.rbac.file = file:/application/rbac_rules.json
      spring.security.oauth2.resourceserver.jwt.issuer-uri = http://basyx-keycloak.basyx.svc.cluster.local:8080/realms/BaSyx
    ingress:
      enabled: true
      host: local.basyx.disco.url

  # Also needs an ingress.
  aas-environment:
    enabled: true
    image:
      name: eclipsebasyx/aas-environment:2.0.0-SNAPSHOT
      pullPolicy: Always
    service:
      port: 8081
    config: |-
      server.port=8081

      basyx.backend = InMemory

      #basyx.environment=file:aas

      logging.level.root=DEBUG

      basyx.cors.allowed-origins=*
      basyx.cors.allowed-methods=GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
      basyx.aasrepository.feature.registryintegration=https://local.basyx.reg.url
      basyx.externalurl=https://local.basyx.env.url
      spring.servlet.multipart.max-file-size=128MB
      spring.servlet.multipart.max-request-size=128MB

      basyx.aasrepository.feature.mqtt.enabled = true
      basyx.submodelrepository.feature.mqtt.enabled = true
      mqtt.clientId=basyx
      mqtt.hostname=local.broker.url
      mqtt.protocol=wss
      mqtt.port=443
      mqtt.username=mqtt-broker-user
      mqtt.password=mqtt-broker-pw
    ingress:
      enabled: true
      host: local.basyx.env.url

  # Needs specific ingress.
  aas-web-ui:
    enabled: false
